### ISSUE TITLE
grid Value Not Reactive with Multiple Vue Instances

### ISSUE THREAD

**Issue by alizadeh118** [reegodev/vue-screen#100]
**Version**
`2.4.0`

**Config**
Using `custom`, but it’s not actually relevant.

**Reproduction link**
https://stackblitz.com/edit/vitejs-vite-zp9pxz

**Describe the bug**
The value of `$grid` is not reactive entirely when used across multiple Vue instances.
This issue also occurs when using the Composition API style.
As I know, it is only reactive in the last Vue instance (in this case app2).
The non-reactive keys are:
- breakpoint
- function-type values (like `tabletAndDown`)

**To Reproduce**
1. Go to Reproduction link.
2. Resize the window to reach desktop.
3. See the difference between values:
`breakpoint` and `tabletAndDown` values are only updated in the latter Vue instance (app2).

![vue-screen](https://github.com/user-attachments/assets/e136423a-3760-4b0d-8d51-0c4f9da2300f)

**Expected behavior**
All values in the `grid` object should be updated and reactive across all instances.

**Comment by reegodev** [comment]
Hey @alizadeh118 , thanks for reporting this.
It was indeed a bug, it should be fixed in 2.4.1.
I've tried your repro with the new version and it looks alright.

Closing this, cheers!
