### ISSUE TITLE
The default tailwind breakpoint is incorrect

### ISSUE THREAD

**Issue by Quineone** [reegodev/vue-screen#11]
For now, the tailwind breakpoint is the same as the bootstrap's
bootstrap: https://github.com/reegodev/vue-screen/blob/develop/src/grids/bootstrap.js
tailwind: https://github.com/reegodev/vue-screen/blob/develop/src/grids/tailwind.js

The tailwind official breakpoint setting : https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js

**Comment by reegodev** [comment]
Hi @Quineone , great catch! Gonnaa fix it asap

**Comment by reegodev** [comment]
Fixed with 1.4.3!
