### ISSUE TITLE
How to detect that lib was initialized successfully? 

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [reegodev/vue-screen#23]
Since there is a slight delay between lib initialization and actual rendering there is no way to tell whether the current brakepoint is actually the one that was set or we just didn't switch to a real one yet since lib is not yet initialized. It would be good if there would be some reactive property that would indicate that lib is initialized and we can actually account for the specified brakepoint.

**Comment by reegodev** [comment]
Hi @AndrewBogdanovTSS, library initialization is synchronous, there should be no delay in detecting the current breakpoint.
Can you provide an example or a better description of your problem?
