### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by Demon000** [reegodev/vue-screen#25]
Plugin install fails with
`Uncaught TypeError: Vue.observable is not a function`

**Comment by reegodev** [comment]
The library does not support Vue3 yet.
Im developing the v2 version that will support Vue3 with both composition API and options API.
As I'm currently quite busy, expect it to come not sooner than the first week of November

**Comment by khari998** [comment]
Hope you get a chance to move this over to Vue 3 soon.

**Comment by reegodev** [comment]
That's the plan @khari998 , got really busy at work lately so i haven't been in the mood of coding in my free time, but Vue 3 version is already at a good point

**Comment by reegodev** [comment]
Hello folks, after endless burnouts i've merged the `next` branch and v2 can start its alpha lifecycle!

v2 brings support for Vue 3 and has some breaking changes. Most notably:

- configuration has been revamped
- the `$screen` object has been split into 2 different objects, `screen` and `grid`, to improve tree shacking and code autocomplete
- callbacks have been removed ( if you heavily relied on them, please open an issue and let's talk about it )

I've replaced the demo site with a dedicated docs website which should cover most questions, [please check it out](https://reegodev.github.io/vue-screen/)

As this is still alpha, some things might change, but i'm quite convinced with the shape of the new API.

To test the new version you can do the following:

```bash
yarn add vue-screen@next
```
In a component
```vue
<script>
import { useScreen, useGrid } from 'vue-screen'
export default {
  setup() {
    const screen = useScreen()
    const grid = useGrid('tailwind')

    return {
      screen,
      grid,
    }
  }
}
</script>
<template>
  <div>
    <p>Screen width is {{ screen.width }}</p>
    <p>Screen height is {{ screen.height }}</p>
    <p>Current breakpoint is {{ grid.breakpoint }}</p>
  </div>
</template>
```
