### ISSUE TITLE
onUnmounted is called when there is no active component instance to be associated with

### ISSUE THREAD

**Issue by jjjrmy** [reegodev/vue-screen#46]
I am using Inertia JS with the example below. I am getting the warning:

`[Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.`

```js
import { createApp } from 'vue'
import VueScreen from 'vue-screen'

// In App.vue
createApp({
    render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => require(`./Pages/${name}`).default,
        }),
})
    .mixin({ methods: { route } })
    .use(InertiaPlugin)
    .use(VueScreen)
    .mount(el);

// In MyComponent.vue
<template>
    <ul>
        <li>Current breakpoint is: {{ $grid.breakpoint }}</li>
        <li>Window width is: {{ $screen.width }}</li>
        <li>Window height is: {{ $screen.height }}</li>
    </ul>
</template>
```

**Comment by reegodev** [comment]
Hi @jjjrmy, thank you for reporting this. Although this is just a warning and has no real consequences on final production builds, i have a fix ready to publish very soon.

**Comment by Kurbezz** [comment]
@reegodev Hi. What's with the new release?

**Comment by reegodev** [comment]
The warning is gone in v2.0.4-alpha.4
