### ISSUE TITLE
Adding conditionnals breakpoints

### ISSUE THREAD

**Issue by Barbapapazes** [reegodev/vue-screen#47]
Adding breakpoints like xsOnly or smAndUp could be really I think !

**Comment by reegodev** [comment]
Hi @Barbapapazes , I've thought about it several times but I've never found a compelling use case.
Your two examples can already be implemented respectively using `!$screen.sm` and `$screen.sm` (breakpoints are mobile-first so sm matches all other breakpoints upwards )

That being said, if you or anyone else can provide use cases for extra grid helpers I'll be happy to discuss them.

**Comment by Barbapapazes** [comment]
Hello, 

For *AndUp, because of the construction of your plugin, it's quite easy.

For *AndDown, I created some function like:

```js
 mdAndDown() {
    return (
      (this.$screen.xs || this.$screen.sm || this.$screen.md) &&
      !this.$screen.lg
    )
  }
```

I think this is juste syntax to facilitate the use of your lib, but it's already very good ! 😍

**Comment by reegodev** [comment]
Your last snippet is correct indeed.

To achieve the same functionality you can use callbacks ( I'm assuming you are using version 1.x for Vue 2. Version 2 will have a similar functionality soon ):

```js
Vue.use(VueScreen, {
    extend: 'tailwind',
    mdAndDown: screen => !screen.lg,
});
```

Now your `$screen` object will contain tailwind breakpoints plus `mdAndDown`.
This way you can customize the grid with your needs.
