### ISSUE TITLE
Using matchMedia instead of window.resize

### ISSUE THREAD

**Issue by nimatrengo** [reegodev/vue-screen#53]
Great library, I like it too much, just I was curios about using matchMedia instead of resizing. can you please explain me why you are using `resize` and matchMedia together in https://github.com/reegodev/vue-screen/blob/master/packages/lib/src/useScreen.ts#L46.  ? 

Thanks a lot.

**Comment by reegodev** [comment]
Hi @nimatrengo , thank you for the kind words.
There are no big differences between using matchMedia and resize event, but i wanted to be as efficient as possible so i opted to only check page dimensions on resize event, which always change, and let a dedicated media query event notify me when orientation changes, which changes very rarely if you listen to the resize event.
