### ISSUE TITLE
small suggested change in docs for Nuxt integration

### ISSUE THREAD

**Issue by udit99** [reegodev/vue-screen#54]
It might be obvious to others who're more experienced with Nuxt but I definitely tripped on this:

When integrating with Nuxt, the variable is $nuxt.$screen and not $screen as listed in the docs [here](https://www.npmjs.com/package/vue-screen#nuxt-module)

**Comment by reegodev** [comment]
Hi @udit99 , can you show me an example of where you use `$nuxt.$screen` rather than `this.$screen`?
