### ISSUE TITLE
wrong breakpoint even when the condition is correct

### ISSUE THREAD

**Issue by lucianamendez** [reegodev/vue-screen#57]
Hi! not sure if I'm doing something wrong or I'm missing a detail.
What I did was to set this screen sizes and some callbacks on my nuxt config file. Everything is working fine except it's showing the 'tablet' breakpoint when its 'desktop'. If I remove the "screen.touch" from the condition it display the correct one but I need to add the touch detection. The weird thing is that the touch value is correct when I log it

Thanks :) 

<img width="618" alt="Screen Shot 2021-09-28 at 17 53 27" src="https://user-images.githubusercontent.com/30813805/135164168-67cb1866-2318-404f-b51c-91da7762a5ba.png">

![Screen Shot 2021-09-28 at 17 54 37](https://user-images.githubusercontent.com/30813805/135165418-71f11cd4-2fbb-469f-9880-07c2391eb8df.png)

**Comment by reegodev** [comment]
Hi @lucianamendez , a reproduction link would really help here.
My guess is that since the touch property is not reactive and is always true on SSR, it is somehow interfering with the current breakpoint calculation

**Comment by lucianamendez** [comment]
Yes, seems like is that. I managed to work around it by moving the conditions to the store when mounting the app and adding a watcher. Thanks!

**Comment by reegodev** [comment]
@lucianamendez New version 1.5.6 should fix your problem. The library was running callbacks before checking for touch support.
If your problem persists, feel free to reopen the issue.
Thanks

**Comment by fernandodevelon** [comment]
I think the problem is still there...
I did a simple test
```
test: (screen)=> screen.breakpoint
```
I then output the two values on the screen
```
{{ $screen.brackpoint }} - {{ $screen.test }}
```
they are different.

**Comment by reegodev** [comment]
@fernandodevelon you are supposed to return a boolean from a callback, returning a string makes it always truthy. 
Also please create a minimal reproduction link so it's easier to spot misconfigurations vs bugs
