### ISSUE TITLE
Leftover console.log in package version

### ISSUE THREAD

**Issue by Anahkiasen** [reegodev/vue-screen#58]
**Version**
`2.1.0-alpha.5`

**Reproduction link**
Fresh install of the package, use `useGrid`

**Describe the bug**
There is a leftover console.log during `createMediaQueries`

![Screenshot 2021-10-28 at 13 22 14](https://user-images.githubusercontent.com/1321596/139246369-0545d812-d407-43e3-b82a-599c5fba2529.png)

**Comment by chemeng** [comment]
@reegodev any chance we can clean this?

**Comment by jmc0228** [comment]
> @reegodev any chance we can clean this?

I second this

**Comment by reegodev** [comment]
Sorry for the delay but I have been quite busy in the past weeks. I'm planning on releasing a fix today

**Comment by chemeng** [comment]
> Sorry for the delay but I have been quite busy in the past weeks. I'm planning on releasing a fix today

thank you

**Comment by reegodev** [comment]
Fixed with version 2.1.0-beta.1
