### ISSUE TITLE
Width and Height on mobile view on Chrome is not correct

### ISSUE THREAD

**Issue by LucianHij** [reegodev/vue-screen#59]
**Version**
2.1.0-alpha.5

**Config**
default

**Describe the bug**
!!! It is happenning on Chrome. 
On Safari and Firefox it is working. 

console log the screen for the window on mobile.
refresh multiple times, is not happenning everytime

**To Reproduce**
![image](https://user-images.githubusercontent.com/11724142/145008680-e4f01d3d-573d-4bb4-8f1a-1a57eb8958e6.png)

**Expected behavior**
sizes to be okay

**Comment by reegodev** [comment]
Hi @LucianHij , would you mind making a reproduction on CodeSandbox / Stackblitz, or a repository with a minimal reproduction? Your screenshot is kinda blurry and there should be no problems between different browsers as far as I'm aware
