### ISSUE TITLE
dont work correctly on nuxt 3 3.4.2

### ISSUE THREAD

**Issue by joseehilton147** [reegodev/vue-screen#80]
**Version**
2.2.0

**Config**
```
{
xs: 320,
sm: 576,
md: 768,
lg: 992,
xl: 1200,
isMobile: screen => screen.xs || screen.sm,
isTablet: screen => screen.md,
isDesktop: screen => screen.lg || screen.xl,
breakpointsOrder: ['xs', 'sm', 'md', 'lg', 'xl'],
}
```

**Describe the bug**
Im setting up the plugin to get some values auto like isTablet or isDesktop and isnt working on page.

![image](https://user-images.githubusercontent.com/53986027/236479337-3986a5a7-768c-4b06-9550-79a1ae34aab9.png)

Here is the nuxt plugin:

```
import VueScreen from 'vue-screen'

export default defineNuxtPlugin(nuxtApp => {
	nuxtApp.vueApp.use(VueScreen, {
		xs: 320,
		sm: 576,
		md: 768,
		lg: 992,
		xl: 1200,
		isMobile: screen => screen.xs || screen.sm,
		isTablet: screen => screen.md,
		isDesktop: screen => screen.lg || screen.xl,
		breakpointsOrder: ['xs', 'sm', 'md', 'lg', 'xl'],
	})
})
```

**Comment by reegodev** [comment]
Hi, you are using the old config from the v1 version, please also make sure to install the library as `vue-screen@next` if you are on Vue 3 / Nuxt 3.
You can see the v2 plugin config [here](https://reegodev.github.io/vue-screen/guide/configuration/plugin.html).
[Here](https://stackblitz.com/edit/nuxt-starter-gxoabl?file=app.vue) is an updated Nuxt 3.4.3 reproduction with your config.

**Comment by Vadimpioner** [comment]
How to solve this problem?
