### ISSUE TITLE
Bootstrap breakpoints

### ISSUE THREAD

**Issue by nWacky** [reegodev/vue-screen#82]
**Version**
2.2.0

**Describe the bug**

In Bootstrap 2 `phones` breakpoint [ends at 480px](https://getbootstrap.com/2.3.2/scaffolding.html#responsive), and bootstrap 3 [starts at 768px](https://getbootstrap.com/docs/3.4/css/#grid-media-queries)

In Bootstrap [4](https://getbootstrap.com/docs/4.6/layout/overview/#responsive-breakpoints) and [5](https://getbootstrap.com/docs/5.3/layout/breakpoints/#available-breakpoints) `sm` breakpoint [starts at 576px](https://github.com/twbs/bootstrap/blob/36293754fffb8b4b8457d7a163eb8c8b7a8970d4/site/data/breakpoints.yml).

In vue-screen 2.2.0 bootstrap's `sm` breakpoint [starts at 480px](https://github.com/reegodev/vue-screen/blob/501730849340f4c0bc7c6e264084ff850e6ea0b0/packages/lib/src/grids/bootstrap.ts#L5). In develop branch it [starts at 576px](https://github.com/reegodev/vue-screen/blob/e549eacb2672584bfa4d10ba109464eb87e1cf8a/src/grids/bootstrap.js#L3)

Perhaps, there's a typo in bootstrap breakpoint value?

**Comment by reegodev** [comment]
Thanks for reporting this, it looks like I messed up the values along the way.
I am going to release a fix very soon to provide more precise breakpoints for different bootstrap versions, eg: `bootstrap3`, `bootstrap4`, etc 

In the mean time please use a custom grid with the correct values

**Comment by reegodev** [comment]
Version 2.3.0 has been released with the fixed breakpoints, now you can choose:

- `bootstrap` / `bootstrap3`
- `bootstrap4`
- `bootstrap5`

https://reegodev.github.io/vue-screen/guide/frameworks/bootstrap.html

**Comment by makroxyz** [comment]
Hi could you tag release 2.3.0 please?
