### ISSUE TITLE
Support for vue-test-utils

### ISSUE THREAD

**Issue by jmariller** [reegodev/vue-screen#85]
**Version**
vue-screen: `2.3.0`
vue: `3.3.4`
@vue/test-utils: `2.3.2`

**Describe the bug**
Following error message is displayed when running Vue Tests on a component that uses vue-screen:
```TypeError: Cannot read properties of undefined (reading 'min')```

**To Reproduce**
1. Create a Vue component that uses vue-screen
2. Write & run a test for that component

**Expected behavior**
Test should run without errors

**Comment by reegodev** [comment]
Hi, can you provide a minimal reproduction link or repo?
There are many ways to setup `@vue/test-utils` based on the assertion library used and environment where the tests are run ( Node, Cypress, Playwright )

**Comment by jmariller** [comment]
Hi, just to let you know I am sorry I did not have time to prepare this yet, but will do shortly.

**Comment by reegodev** [comment]
Hey @jmariller , I've published a new version with some compatibility fixes when running the library in jsdom environments.
Can you try to update to v2.3.2 and see if your issues are fixed?
Remember that in jsdom the window size is set at 1024x768, so you might get unexpected results in your tests if you are checking things related to `useGrid`/`useScreen`

**Comment by jmariller** [comment]
Hi @reegodev thank you so much, my issues are indeed fixed with this new version :+1: Closing this issue :)
