### ISSUE TITLE
grid is not reactive in vite , screen still works though

### ISSUE THREAD

**Issue by shaderbytes** [reegodev/vue-screen#88]
"vue-screen": "^2.3.2" 
"vite": "^4.4.11"

grid is not reactive anymore? screen object is still reactive , eg 

```
const grid = useGrid("bootstrap");
const screen = useScreen()
```

```
 <div>{{  grid.breakpoint  }}</div>
    <p>Screen width is {{ screen.width }}</p>
```

screen.width updates when changing screensizes
grid.breakpoint DOES NOT UPDATE when changing screensizes

**Comment by reegodev** [comment]
Hi @shaderbytes , you need to provide a reproduction case because the code that you provided does not seem to have any problem.

I created a stackblitz project and everything looks fine.
https://stackblitz.com/edit/vitejs-vite-qgazqo?file=src%2FApp.vue
