### ISSUE TITLE
Using vue-screen as plugin and accessing in composition API script

### ISSUE THREAD

**Issue by 21stcn** [reegodev/vue-screen#90]
### Discussed in https://github.com/reegodev/vue-screen/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **21stcn** March 11, 2024</sup>
Looking for some pointers for correct usage please. 

I am using vue-screen as a plugin (as described in [docs](https://reegodev.github.io/vue-screen/guide/configuration/plugin.html)):

```js
//plugins/screen.js

import VueScreen from "vue-screen";
import tailwindScreens from "#twcss/theme/screens";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueScreen, {
    grid: {
      base: "0px",
      ...tailwindScreens,
    },
  });
});
```

In this way I can access $screen and $grid within any template in the app, which is functioning as expected:
```html
<button v-show="$grid.lg">Button</button>
```

How can I access $grid and $screen with this global configuration from within the composition api? For example:

```js
const initHome = () => {
     
  if ($screen.touch){
    logic
  }
};
```

Is it necessary to use a composable ([as described in docs](https://reegodev.github.io/vue-screen/guide/examples/shared-config.html)) alongside the plugin config to use this single config in the script of every component? Ideally I would like to just configure the plugin and have $screen and $grid available in the composition api. 

Thanks for your help!

</div>

**Comment by 21stcn** [comment]
Not sure if the correct approach but using a composable to use `screen` and `grid` within script setup logic.

```
import { useScreen, useGrid } from "vue-screen";
import tailwindScreens from "#twcss/theme/screens";

export const screen = useScreen();
export const grid = useGrid({
  base: "0px",
  ...tailwindScreens,
});
```

Slight redundancy redefining grid (as also done in the plugin) but working.

**Comment by reegodev** [comment]
Hi @21stcn 
Your second approach is preferred when using the composition API, you can find an example here https://reegodev.github.io/vue-screen/guide/examples/shared-config.html

If you really want to use the plugin version, you can access the global properties in a component directly in the template:

```vue
import { getCurrentInstance } from 'vue'
<script setup>
const internalInstance = getCurrentInstance()

console.log({
 screen: internalInstance.
});
</script>

<template>
<p>{{ $screen }}</p>
<p>{{ $grid }}</p>
</template>
```

or if you need to access them in the component logic, you can use `getCurrentInstance`:
```vue
import { getCurrentInstance } from 'vue'
<script setup>
const internalInstance = getCurrentInstance()

console.log({
  screen: internalInstance.appContext.config.globalProperties.$screen,
  grid: internalInstance.appContext.config.globalProperties.$grid,
});
</script>
```
Although with this method, properties won't be reactive. `getCurrentInstance` has been removed from Vue docs since I initially wrote the docs, I need to publish a new version with a different approach

**Comment by 21stcn** [comment]
Ok perfect. Thanks very much for the explanation. I'll use the composable approach.

Thanks!

**Comment by reegodev** [comment]
With version `2.4.0` you can also use `inject` to obtain the `screen` and `grid` properties when using the plugin configuration.
https://reegodev.github.io/vue-screen/guide/configuration/plugin.html#using-screen-and-grid-properties-in-your-components
